version: '3'

services:
  python-fastapi-backend:
    build:
      context: ./python-fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models
    command: python app.py --model /models/model.onnx --host 0.0.0.0 --port 8000
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  djl-serving-backend:
    build:
      context: ./djl-serving-backend
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./models:/opt/djl/models/llm-onnx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  models:
    driver: local
